// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />

import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: "./apps/.env" });

export default defineConfig({
  schema: "infra/prisma/schema.prisma",
  migrations: {
    path: "infra/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});